sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ashleychristensen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ashleychristensen/react-test npm test

after_success:
  - docker build -t /multi-client ./client
  - docker build -t ashleychristensen/multi-nginx ./nginx
  - docker build -t ashleychristensen/multi-server ./server
  - docker build -t ashleychristensen/multi-worker ./worker
  # Log in to the docker CLI, working on below command
  - docker login --username "$DOCKER_ID"  --password "$DOCKER_PASSWORD"
  # Take those images and push them to docker hub
  - docker push ashleychristensen/multi-client
  - docker push ashleychristensen/multi-nginx
  - docker push ashleychristensen/multi-server
  - docker push ashleychristensen/multi-worker
